apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cli-plugin-test
  description: Includes commands to run integration and unit tests for VTEX apps
  tags:
    - typescript
    - oclif
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex/cli-plugin-test
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: Y58GE1TE
spec:
  lifecycle: stable
  owner: te-0029
  type: cli-plugin
  dependsOn: []
  subcomponentOf: toolbelt
