- name: cli-plugin-test
  build:
    provider: dkcicd
    pipelines:
      - name: techdocs-v1
        parameters:
          entityReference: default/component/cli-plugin-test
          sourceDir: ./
        when:
          - event: push
            source: branch
            regex: master
            path:
              - "docs/**"
              - README.md
              - .vtex/deployment.yaml